name: navi_light_example
description: Demonstrates how to use the navi_light plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.5.7
  navi_light:
    path: ../
flutter:
  uses-material-design: true
